In [12]:
# ==============================
# JSON → Pandas DataFrame (Google Colab)
# ==============================

# Install dependencies (optional, Colab usually includes pandas)
!pip install pandas

# ---- 1️⃣ Import libraries ----
import json
import pandas as pd

# ---- 2️⃣ Upload JSON file ----
# You can upload your file manually in Colab or mount Google Drive if needed.
# Example: from google.colab import files
# files.upload()

# For demonstration, assuming file is named 'sample (1).json'
file_path = '/content/sample.json'

# ---- 3️⃣ Load JSON ----
with open(file_path, 'r') as file:
    data = json.load(file)

# ---- 4️⃣ Normalize JSON into flat records ----
records = []
for customer in data:
    for order in customer['orders']:
        for item in order['items']:
            records.append({
                'customer_id': customer['customer_id'],
                'order_id': order['order_id'],
                'product': item['product'],
                'quantity': item['quantity'],
                'total': order['total']
            })

# ---- 5️⃣ Create DataFrame ----
df = pd.DataFrame(records)

# ---- 6️⃣ Display the DataFrame ----
print("✅ Flattened DataFrame:")
print(df)

# ---- 7️⃣ (Optional) Export to CSV ----
# df.to_csv('flattened_orders.csv', index=False)
# print("CSV file saved as 'flattened_orders.csv'")


✅ Flattened DataFrame:
   customer_id  order_id     product  quantity  total
0          101      5001      Laptop         1  120.5
1          101      5001       Mouse         1  120.5
2          102      5002  Smartphone         1  250.0
3          102      5002     Charger         2  250.0
4          102      5003  Headphones         1   75.0


In [13]:
# ==============================
# JSON → Flat DataFrame → JSON
# ==============================

import json
import pandas as pd

# ---- 1️⃣ Load the original JSON ----
with open('/content/sample.json', 'r') as file:
    data = json.load(file)

# ---- 2️⃣ Normalize the JSON structure ----
records = []
for customer in data:
    for order in customer['orders']:
        for item in order['items']:
            records.append({
                'customer_id': customer['customer_id'],
                'order_id': order['order_id'],
                'product': item['product'],
                'quantity': item['quantity'],
                'total': order['total']
            })

# ---- 3️⃣ Create DataFrame ----
df = pd.DataFrame(records)

# ---- 4️⃣ Save as a new JSON file ----
output_file = 'flattened_orders.json'
df.to_json(output_file, orient='records', indent=4)

# ---- 5️⃣ Display confirmation ----
print(f"✅ Flattened data saved to: {output_file}")

# ---- 6️⃣ Generate download link (Colab only) ----
from google.colab import files
files.download(output_file)


✅ Flattened data saved to: flattened_orders.json


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [14]:
# Standardizing common terms
common_terms = {
    "Dr.": "Doctor",
    "NYC": "New York",
    "N.Y.": "New York",
    "USD": "dollars",
    "$": "dollars"
}

def standardize_terms(text, replacements):
    for key, value in replacements.items():
        text = text.replace(key, value)
    return text

# Example
text = "Dr. Smith is based in NYC and charges 100 USD."
clean_text = standardize_terms(text, common_terms)
print(clean_text)
# Output: "Doctor Smith is based in New York and charges 100 dollars."

Doctor Smith is based in New York and charges 100 dollars.


In [15]:
!pip install contractions


In [23]:
import re
import string

text = """Thís ís à próblemátic téxt fíle!! It contains    **extra spaces** ,,,,, special characters!!!💥🔥🚀
Some words are misspelleddd,   and encoding  issues   liké thís cäusé problëms.
Prices are inconsistent:  $29.99, 29.99 USD, 29,99$.
Emails & phone numbers may be embedded: contact@domain.com, (123)-456-7890.
Repeated punctuations!!!!! should be removed, along with **random symbols** like @@,##.
stopwords like "the", "is", and "a" appear often.
HTML tags might be present: <div>This is inside a div</div>
And sometimes, contractions won't expand: "can't", "won't", "shouldn't".
Random numeric values: 123456, 98765, 2024.
"""

# 1️⃣ Remove HTML tags
text = re.sub(r'<.*?>', '', text)

# 2️⃣ Remove emails, phone numbers, and prices
text = re.sub(r'\S+@\S+', '', text)                     # emails
text = re.sub(r'\(?\b\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b', '', text)  # phone numbers
text = re.sub(r'\$?\d+(?:[\.,]\d+)?(?:\s?USD)?', '', text)  # prices

# 3️⃣ Remove punctuation, symbols, emojis, and numbers
text = re.sub(r'[^\w\s]', ' ', text)                    # keep letters/numbers
text = re.sub(r'[\U00010000-\U0010ffff]', '', text)     # remove emojis
text = re.sub(r'\d+', '', text)                         # remove numbers

# 4️⃣ Normalize spaces
text = re.sub(r'\s+', ' ', text).strip()

# 5️⃣ Convert to lowercase
clean_text = text.lower()

# 6️⃣ Remove basic stopwords manually
stopwords = {'the', 'is', 'a', 'and', 'of', 'to', 'in', 'it', 'this', 'that', 'on', 'for', 'be'}
words = [word for word in clean_text.split() if word not in stopwords]
clean_text = ' '.join(words)

# 7️⃣ Print or save result
print(clean_text)

with open("cleaned_text.txt", "w") as f:
    f.write(clean_text)


thís ís à próblemátic téxt fíle contains extra spaces special characters some words are misspelleddd encoding issues liké thís cäusé problëms prices are inconsistent emails phone numbers may embedded repeated punctuations should removed along with random symbols like stopwords like appear often html tags might present inside div sometimes contractions won t expand can t won t shouldn t random numeric values


In [24]:
import numpy as np

# A small 3x3 grayscale image (each number is a pixel intensity)
gray_img = np.array([
    [0, 255, 100],
    [50, 128, 200],
    [30, 180, 220]
])

print(gray_img)

[[  0 255 100]
 [ 50 128 200]
 [ 30 180 220]]
